import { Theme } from "../../ui/styles/theme.slint";

export global MediaAdapter {
    in-out property <string> status: "stopped";
    in-out property <bool> has-player: true;
    in-out property <string> title: "Sin música";
    in-out property <string> artist: "Artista";

    callback play-pause();
    callback next();
    callback previous();
    callback toggle-control-center();
}

export component MediaWidget {
    HorizontalLayout {
        horizontal-stretch: 0;
        alignment: center;
        height: 28px;

        TouchArea {
            Rectangle {
                background: Theme.surface;
                border-radius: 20px;

                HorizontalLayout {
                    alignment: center;
                    spacing: 6px;
                    padding: 2px;

                    VerticalLayout {
                        alignment: center;
                        padding-left: 1px;

                        Rectangle {
                            width: 22px;
                            height: 22px;
                            border-radius: 11px;
                            background: Theme.surface-container-highest;
                            drop-shadow-color: #00000079;
                            drop-shadow-offset-y: 1px;
                            drop-shadow-offset-x: 1px;
                            drop-shadow-blur: 3px;

                            //svg icon con un padding negativo para que este centrado
                            VerticalLayout {
                                alignment: center;
                                padding: 3px;
                                HorizontalLayout {
                                    alignment: center;
                                    padding-left: -0.01px;
                                    Image {
                                        source: @image-url("../../assets/icons/dashboard.svg");
                                        width: 14px;
                                        height: 14px;
                                        colorize: Theme.on-surface;
                                    }
                                }
                            }
                        }
                    }

                    VerticalLayout {
                        alignment: center;

                        Rectangle {
                            background: Theme.surface-container-high;
                            border-radius: 6px;
                            drop-shadow-color: #00000079;
                            drop-shadow-offset-y: 1px;
                            drop-shadow-offset-x: 1px;
                            drop-shadow-blur: 3px;

                            HorizontalLayout {
                                spacing: 5px;
                                padding: 3px;

                                VerticalLayout {
                                    alignment: center;
                                    padding: -1px;
                                    padding-left: -0px;

                                    Image {
                                        source: MediaAdapter.has-player ? @image-url("../../assets/icons/motion_play.svg") : @image-url("../../assets/icons/music_off.svg");
                                        image-fit: contain;
                                        colorize: Theme.on-surface;
                                    }
                                }

                                Text {
                                    visible: MediaAdapter.artist != "";
                                    font-weight: 600;
                                    vertical-alignment: center;
                                    text: MediaAdapter.artist;
                                    font-family: Theme.font-family;
                                    font-size: 10px;
                                    color: Theme.on-surface-variant;
                                    max-width: 70px;
                                    overflow: elide;
                                }

                                Text {
                                    visible: MediaAdapter.title != "";
                                    vertical-alignment: center;
                                    text: MediaAdapter.title;
                                    font-family: Theme.font-family;
                                    font-size: 10px;
                                    color: Theme.on-surface;
                                    max-width: 100px;
                                    overflow: elide;
                                }

                                Rectangle {
                                    background: Theme.surface-container-highest;
                                    border-radius: 4px;
                                    drop-shadow-color: #00000079;
                                    drop-shadow-offset-y: 1px;
                                    drop-shadow-offset-x: 1px;
                                    drop-shadow-blur: 3px;

                                    VerticalLayout {
                                        TouchArea {
                                            clicked => {
                                                MediaAdapter.play-pause();
                                            }
                                            opacity: MediaAdapter.has-player ? 1 : 0.3;

                                            Image {
                                                source: MediaAdapter.status == "playing" ? @image-url("../../assets/icons/pause.svg") : @image-url("../../assets/icons/play_arrow.svg");
                                                width: 16px;
                                                height: 16px;
                                                image-fit: contain;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }

                    VerticalLayout {
                        alignment: center;
                        padding-right: 1px;

                        Rectangle {
                            width: 22px;
                            height: 22px;
                            border-radius: 11px;
                            background: Theme.surface-container-highest;
                            drop-shadow-color: #00000079;
                            drop-shadow-offset-y: 1px;
                            drop-shadow-offset-x: 1px;
                            drop-shadow-blur: 3px;

                            Image {
                                source: @image-url("../../assets/icons/notifications_active.svg");
                                width: 14px;
                                colorize: Theme.on-surface;
                            }
                        }
                    }
                }
            }

            clicked => {
                MediaAdapter.toggle-control-center();
            }
        }
    }
}
