import { Theme } from "../../ui/styles/theme.slint";

export global MediaAdapter {
    in-out property <string> status: "stopped";
    in-out property <bool> has-player: false;
    in-out property <string> title: "Sin música";
    in-out property <string> artist: "";

    callback play-pause();
    callback next();
    callback previous();
}

export component MediaWidget {
    callback clicked;

    Rectangle {
        vertical-stretch: 1;

        HorizontalLayout {
            horizontal-stretch: 0;
            alignment: start;

            TouchArea {
                HorizontalLayout {
                    spacing: 4px;

                    VerticalLayout {
                        alignment: center;
                        padding-right: 0px;

                        icon-rect := Rectangle {
                            width: 43px;

                            Image {
                                source: MediaAdapter.has-player ? @image-url("../../assets/icons/motion_play.svg") : @image-url("../../assets/icons/music_off.svg");
                                height: 22px;
                                image-fit: contain;
                            }
                        }
                    }

                    // VerticalLayout {
                    //     alignment: center;

                    //     Rectangle {
                    //         clip: true;
                    //         width: 22px;
                    //         height: 22px;
                    //         border-radius: Theme.music_album_border_radius * 1px;
                    //         background: #a7a7a778;
                    //         Image {               
                    //             // source: root.album-art;
                    //             width: 22px;
                    //             height: 22px;
                    //             image-fit: cover;
                    //         }
                    //     }
                    // }

                    VerticalLayout {
                        alignment: center;
                        padding-top: 1px;
                        spacing: -2px;

                        Text {
                            font-weight: 600;
                            vertical-alignment: bottom;
                            text: MediaAdapter.artist;
                            font-family: Theme.font-family;
                            font-size: 9.5px;
                            color: Theme.music_artist_color;
                            max-width: 150px;
                            overflow: elide;
                        }

                        Text {
                            font-weight: 600;
                            vertical-alignment: bottom;
                            text: MediaAdapter.title;
                            font-family: Theme.font-family;
                            font-size: 11px;
                            color: Theme.foreground;
                            max-width: 150px;
                            overflow: elide;
                        }
                    }
                }

                clicked => {
                    root.clicked();
                }
            }
        }
    }
}
