import { Theme } from "../../ui/styles/theme.slint";

export global ColorizeAdapter {
    callback colorize-clicked();
}

export component ColorizeWidget {
    Rectangle {
        vertical-stretch: 1;

        VerticalLayout {
            alignment: center;

            hover_rect := Rectangle {
                height: 30px;
                background: touch_area.has-hover ? #e7e8eb2f : transparent;
                border-width: 1px;
                border-color: touch_area.has-hover ? #ffffff0e : transparent;
                border-radius: 4px;

                VerticalLayout {
                    alignment: center;
                    padding-left: 6px;
                    padding-right: 6px;

                    Image {
                        source: @image-url("../../assets/icons/colorize.svg");
                        width: 16px;
                        height: 16px;
                        image-fit: contain;
                        colorize: Theme.foreground-icon;
                    }
                }
            }
        }

        touch_area := TouchArea {
            clicked => { ColorizeAdapter.colorize-clicked(); }
        }
    }
}
