import { Theme } from "../../ui/styles/theme.slint";

export global ColorizeAdapter {
    callback colorize-clicked();
}

export component ColorizeWidget {
    VerticalLayout {
        alignment: center;

        Rectangle {
            width: 28px;
            height: 28px;
            border-radius: 14px;
            border-width: 2px;
            border-color: touch_area.has-hover ? #ffffff42 : transparent;
            background: touch_area.has-hover ? #262722ed : Theme.workspaces_bg_color;

            Image {
                source: @image-url("../../assets/icons/colorize.svg");
                width: 16px;
                height: 16px;
                image-fit: contain;
                colorize: Theme.foreground-icon;
            }
        }
    }

    touch_area := TouchArea {
        clicked => {
            ColorizeAdapter.colorize-clicked();
        }
    }
}
