import { Theme } from "../../ui/styles/theme.slint";

export global WorkspacesAdapter {
    in-out property <int> active-workspace: 1;
    in-out property <[bool]> workspace-occupied: [true, true, false, true];
    in-out property <int> total-workspaces: 10;
    in-out property <[string]> workspace-format: [];
}

export component WorkspacesWidget {
    private property <length> button-size: 20px;
    private property <length> button-spacing: 3px;
    private property <length> margin: 2px;

    VerticalLayout {
        alignment: center;

        Rectangle {
            background: Theme.workspaces_bg_color;
            border-radius: Theme.workspaces_border_radius * 1px;

            HorizontalLayout {
                alignment: center;
                padding: 4px;

                for i in WorkspacesAdapter.total-workspaces: Rectangle {
                    width: root.button-size;
                    height: root.button-size;

                    private property <bool> occupied:
                                i < WorkspacesAdapter.workspace-occupied.length && WorkspacesAdapter.workspace-occupied[i];

                    private property <bool> isActive:
                                i == WorkspacesAdapter.active-workspace - 1;

                    private property <bool> leftFilled:
                                i > 0 && i - 1 < WorkspacesAdapter.workspace-occupied.length && WorkspacesAdapter.workspace-occupied[i - 1];

                    private property <bool> rightFilled:
                                i + 1 < WorkspacesAdapter.workspace-occupied.length && WorkspacesAdapter.workspace-occupied[i + 1];

                    Rectangle {
                        border-top-left-radius: !leftFilled ? root.button-size / 2 : 0px;
                        border-bottom-left-radius: !leftFilled ? root.button-size / 2 : 0px;
                        border-top-right-radius: !rightFilled ? root.button-size / 2 : 0px;
                        border-bottom-right-radius: !rightFilled ? root.button-size / 2 : 0px;
                        background: occupied ? Theme.workspaces_occupied_bg : #00000000;
                        opacity: occupied ? 1 : 0.0;
                    }

                    if (isActive): Rectangle {
                        width: root.button-size * 0.70;
                        height: root.button-size * 0.70;

                        border-radius: self.width / 2;
                        background: Theme.workspaces_active_color;

                        x: (root.button-size - self.width) / 2;
                        y: (root.button-size - self.height) / 2;

                        drop-shadow-color: #00000079;
                        drop-shadow-offset-y: 1px;
                        drop-shadow-offset-x: 1px;
                        drop-shadow-blur: 3px;
                    }
                    Rectangle {
                        width: root.button-size * 0.20;
                        height: root.button-size * 0.20;

                        border-radius: self.width / 2;
                        background: isActive ? Theme.workspaces_text_active : occupied ? Theme.workspaces_text_occupied : Theme.workspaces_text_free;

                        x: (root.button-size - self.width) / 2;
                        y: (root.button-size - self.height) / 2;

                        drop-shadow-color: #00000079;
                        drop-shadow-offset-y: 1px;
                        drop-shadow-offset-x: 1px;
                        drop-shadow-blur: 3px;
                    }

                    // Text {
                            //     // text: i < WorkspacesAdapter.workspace-format.length ? WorkspacesAdapter.workspace-format[i] : i + 1;
                            //     text: i < WorkspacesAdapter.workspace-format.length ? "3" : "";
                            //     font-size: 10px;
                            //     font-weight: 600;
                            //     font-family: Theme.font-family;
                            //     color: isActive ? Theme.workspaces_text_active : occupied ? Theme.workspaces_text_occupied : Theme.workspaces_text_free;
                            // }
                        // }
                }
            }
        }
    }
}
