import "../fonts/MaterialSymbolsRounded-Regular.ttf";

export global Theme {
    in-out property <color> background: #1e1e1f00;
    in-out property <color> foreground: #cdd6f4;
    in-out property <color> accent: #89b4fa;
    in-out property <color> success: #a6e3a1;
    in-out property <color> warning: #f9e2af;
    in-out property <color> error: #f38ba8;
    
    in-out property <length> bar-height: 34px;
    in-out property <length> icon-size: 16px;
    in-out property <length> padding: 0px;
    in-out property <length> spacing: 8px;
    
    in-out property <string> font-family: "Rubik";
    in-out property <string> icon-font-family: "Material Symbols Rounded";
    in-out property <length> font-size: 15px;
}