import "../fonts/MaterialSymbolsRounded-Regular.ttf";

export global Theme {
    in-out property <color> background: #0808080f;
    in-out property <color> foreground: #bac7bf;
    in-out property <color> foreground-icon: #c9dfc7;
    in-out property <color> accent: #89b4fa;
    in-out property <color> success: #a6e3a1;
    in-out property <color> warning: #f9e2af;
    in-out property <color> error: #f38ba8;
    
    in-out property <length> bar-height: 38px;
    in-out property <length> icon-size: 16px;
    in-out property <length> padding: 0px;
    in-out property <length> spacing: 8px;
    
    in-out property <string> font-family: "Rubik";
    in-out property <string> icon-font-family: "Material Symbols Rounded";
    in-out property <length> font-size: 15px;

    in-out property<color> workspaces_bg_color: #1e1f1bf6;
    in-out property<color> workspaces_active_color: #B4CCC1;
    in-out property<color> workspaces_occupied_bg: #303934;
    in-out property<color> workspaces_text_active: #303934;
    in-out property<color> workspaces_text_occupied: #B4C0B9;
    in-out property<color> workspaces_text_free: #868686;
    in-out property<int> workspaces_border_radius: 14;

    in-out property<color> music_artist_color: #85948d;
    in-out property<int> music_album_border_radius: 4;
}