[display]
height = 38
edge = "top"
width = 1366

[theme]
background = "#0808080f"
foreground = "#bac7bf"
accent = "#89b4fa"

[widgets]
battery = true
network = true
bluetooth = true
clock = true
media = true
workspaces = true
screenshot = true

[workspaces]
total-workspaces = 8
# Por defecto: numeros [1,2,3,4,5,6,7,8,9,10]
# Si quieres usar kanji japoneses u otros caracteres, especificalos:
# format = ["一","二","三","四","五","六","七","八","九","十"]