[display]
height = 38
edge = "top"
width = 1366

[theme]
background = "#0808080f"
foreground = "#bac7bf"
accent = "#89b4fa"

[widget.workspaces]
bg_color = "#1e1f1bf6"
active_color = "#B4CCC1"
occupied_bg = "#303934"
text_active = "#303934"
text_occupied = "#B4C0B9"
text_free = "#868686"
border_radius = 14

[widget.music_icon]
artist_color = "#85948d"
album_border_radius = 4

[widgets]
battery = true
network = true
bluetooth = true
clock = true
media = true
workspaces = true
screenshot = true

[workspaces]
total-workspaces = 8
# Por defecto: numeros [1,2,3,4,5,6,7,8,9,10]
# Si quieres usar kanji japoneses u otros caracteres, especificalos:
# format = ["一","二","三","四","五","六","七","八","九","十"]