import { Theme } from "../../../ui/styles/theme.slint";

export component NotificationHistory {

    Rectangle {
        border-radius: 12px;
        background: Theme.surface-container-high;

        VerticalLayout {
            padding: 8px;
            spacing: 10px;

            Rectangle {
                background: Theme.surface-container;
                border-radius: 8px;

                HorizontalLayout {
                    padding: 5px;

                    Text {
                        text: "Notifications";
                        font-family: Theme.font-family;
                        font-size: 12px;
                        font-weight: 600;
                        color: Theme.on-surface;
                        horizontal-stretch: 1;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                    }

                    Rectangle {
                        width: 26px;
                        height: 26px;
                        border-radius: 5px;
                        background: Theme.surface-container-high;
                        Text {
                            text: "mop";
                            font-family: Theme.icon-font-family;
                            font-size: 14px;
                            color: Theme.on-surface;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                        }
                    }
                }
            }

            Rectangle {
                background: transparent;

                VerticalLayout {
                    vertical-stretch: 1;
                    spacing: 5px;

                    Rectangle {
                        height: 56px;
                        border-radius: 10px;
                        background: Theme.surface-container;

                        VerticalLayout {
                            padding: 8px;
                            alignment: center;

                            HorizontalLayout {
                                spacing: 8px;

                                Rectangle {
                                    width: 32px;
                                    height: 32px;
                                    border-radius: 8px;
                                    background: Theme.primary;
                                    Text {
                                        text: "mail";
                                        font-family: Theme.icon-font-family;
                                        font-size: 16px;
                                        color: Theme.on-primary;
                                        horizontal-alignment: center;
                                        vertical-alignment: center;
                                    }
                                }

                                VerticalLayout {
                                    spacing: 2px;
                                    Text {
                                        text: "Mensaje";
                                        font-family: Theme.font-family;
                                        font-size: 11px;
                                        font-weight: 600;
                                        color: Theme.on-surface;
                                    }

                                    Text {
                                        text: "Hola que haces?";
                                        font-family: Theme.font-family;
                                        font-size: 10px;
                                        color: Theme.on-surface-variant;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
