import { Theme } from "../../ui/styles/theme.slint";

export global ClockAdapter {
    in-out property <string> current-time: "12:00 PM";
    in-out property <string> current-date: "Mon 04/09";
}

export component ClockWidget {
    Rectangle {
        vertical-stretch: 1;
        
        VerticalLayout {
            padding-left: 6px;
            padding-right: 6px;
            alignment: center;
            
            HorizontalLayout {
                spacing: 4px;
                alignment: center;
                
                Text {
                    text: ClockAdapter.current-time;
                    font-family: Theme.font-family;
                    font-size: Theme.font-size;
                    color: Theme.foreground;
                }
                
                Text {
                    text: ClockAdapter.current-date;
                    font-family: Theme.font-family;
                    font-size: Theme.font-size;
                    color: Theme.foreground;
                }
            }
        }
    }
}
