import { Theme } from "../../ui/styles/theme.slint";

export global ClockAdapter {
    in-out property <string> current-time: "12:00 PM";
    in-out property <string> current-date: "Mon 04/09";
}

export component ClockWidget {

    VerticalLayout {
        alignment: center;

        Rectangle {
            height: 28px;
            border-radius: 14px;
            background: Theme.workspaces_bg_color;

            HorizontalLayout {
                spacing: 4px;
                alignment: center;
                padding-left: 10px;
                padding-right: 10px;

                Text {
                    text: ClockAdapter.current-time;
                    font-family: Theme.font-family;
                    font-size: Theme.font-size;
                    color: Theme.foreground;
                    vertical-alignment: center;
                }

                Text {
                    text: "|";
                    font-family: Theme.font-family;
                    font-size: Theme.font-size;
                    color: #ffffff26;
                    vertical-alignment: center;
                }

                Text {
                    text: ClockAdapter.current-date;
                    font-family: Theme.font-family;
                    font-size: Theme.font-size;
                    color: Theme.foreground;
                    vertical-alignment: center;
                }
            }
        }
    }
}
