import { Theme } from "../../ui/styles/theme.slint";

export component ClockWidget {
    in-out property <string> time: "12:00 PM";
    in-out property <string> date: "Mon 04/09";
    
    Rectangle {
        vertical-stretch: 1;
        
        VerticalLayout {
            padding-left: 6px;
            padding-right: 6px;
            alignment: center;
            
            HorizontalLayout {
                spacing: 4px;
                alignment: center;
                
                Text {
                    text: root.time;
                    font-family: Theme.font-family;
                    font-size: Theme.font-size;
                    color: Theme.foreground;
                }
                
                Text {
                    text: root.date;
                    font-family: Theme.font-family;
                    font-size: Theme.font-size;
                    color: Theme.foreground;
                }
            }
        }
    }
}
