import { ScreenshotAdapter } from "../app/screenshot/screenshot.slint";
import { ClockAdapter } from "../app/clock/clock.slint";
import { ArticleAdapter } from "../app/article/article.slint";
import { BluetoothAdapter } from "../app/bluetooth/bluetooth.slint";
import { ColorizeAdapter } from "../app/colorize/colorize.slint";
import { NetworkAdapter } from "../app/network/network.slint";
import { BatteryAdapter } from "../app/battery/battery.slint";
import { WorkspacesAdapter } from "../app/workspaces/workspaces.slint";
import { StatusBarWindow } from "bar.slint";
import { ControlCenter } from "../app/control_center/control_center.slint";
import { MediaAdapter } from "../app/media/media.slint";
import { Theme } from "styles/theme.slint";
export { StatusBarWindow, ControlCenter, MediaAdapter, Theme, ScreenshotAdapter, ClockAdapter, ArticleAdapter, BluetoothAdapter, ColorizeAdapter, NetworkAdapter, BatteryAdapter, WorkspacesAdapter }
