import { Theme } from "styles/theme.slint";
import { ClockWidget } from "../app/clock/clock.slint";
import { BatteryWidget } from "../app/battery/battery.slint";
import { NetworkWidget } from "../app/network/network.slint";
import { BluetoothWidget } from "../app/bluetooth/bluetooth.slint";
import { WorkspacesWidget } from "../app/workspaces/workspaces.slint";
import { ScreenshotWidget } from "../app/screenshot/screenshot.slint";
import { ColorizeWidget } from "../app/colorize/colorize.slint";
import { ArticleWidget } from "../app/article/article.slint";
import { MediaWidget } from "../app/media/media.slint";

export component StatusBarWindow inherits Window {
    title: "Barrita";
    no-frame: true;
    background: transparent;
    always-on-top: true;
    x: 0;
    y: 0;
    width: 1366px;
    height: Theme.bar-height;

    callback popup_toggle();
    callback media_play_pause();
    callback media_next();
    callback media_previous();

    touch_area := TouchArea {
        opacity: touch_area.has-hover ? 1.0 : 0.999;
        Rectangle {
            min-height: Theme.bar-height;

            HorizontalLayout {
                spacing: 0px;
                padding-left: 10px;

                MediaWidget {
                    horizontal-stretch: 1;
                    max-width: parent.width / 3;

                    clicked => {
                        root.popup_toggle();
                    }
                }

                WorkspacesWidget {
                    horizontal-stretch: 1;
                    max-width: parent.width / 3;
                }

                HorizontalLayout {
                    horizontal-stretch: 1;
                    max-width: parent.width / 3;
                    alignment: end;
                    padding-right: 10px;

                    ScreenshotWidget { }

                    ColorizeWidget { }

                    ArticleWidget { }

                    ClockWidget { }

                    BatteryWidget { }

                    NetworkWidget { }

                    BluetoothWidget { }
                }
            }
        }
    }
}
