import { Theme } from "styles/theme.slint";
import { ClockWidget } from "widgets/clock.slint";
import { BatteryWidget } from "widgets/battery.slint";
import { NetworkWidget } from "widgets/network.slint";
import { BluetoothWidget } from "widgets/bluetooth.slint";
import { WorkspacesWidget } from "widgets/workspaces.slint";
import { ScreenshotWidget } from "widgets/screenshot.slint";
import { ColorizeWidget } from "widgets/colorize.slint";
import { MusicIconWidget } from "widgets/music_icon.slint";

export component StatusBarWindow inherits Window {
    title: "Barrita";
    no-frame: true;
    background: transparent;
    always-on-top: true;
    x: 0;
    y: 0;
    width: 1366px;
    height: Theme.bar-height;
    
    in-out property <string> time: "12:00 PM";
    in-out property <string> date: "Mon 04/09";
    
    in-out property <string> battery-percentage: "100%";
    in-out property <bool> battery-charging: false;
    in-out property <string> battery-icon: "battery_6_bar";
    
    in-out property <string> network-status: "WiFi";
    in-out property <bool> network-connected: true;
    in-out property <string> network-icon: "wifi";
    
    in-out property <bool> bluetooth-connected: false;
    
    in-out property <string> media-status: "stopped";
    in-out property <bool> media-has-player: false;
    in-out property <string> media-title: "Sin música";
    in-out property <string> media-artist: "";
    in-out property <image> media-album-art;
    in-out property <float> media-progress: 0.0;
    in-out property <string> media-progress-time: "0:00";
    in-out property <string> media-total-time: "0:00";
    
    in-out property <int> active-workspace: 1;
    in-out property <[bool]> workspace-occupied: [];
    in-out property <bool> music-popup-visible: false;
    
    callback popup_toggle();
    callback media_play_pause();
    callback media_next();
    callback media_previous();
    
    Rectangle {
        min-height: Theme.bar-height;
        // background: Theme.background;
        // opacity: 0.95;
        
        HorizontalLayout {
            spacing: 0px;
            padding-left: 10px;
                               
            MusicIconWidget {
                horizontal-stretch: 1;
                max-width: parent.width / 3;
                status: root.media-status;
                has-player: root.media-has-player;
                title: root.media-title;
                artist: root.media-artist;
                album-art: root.media-album-art;

                clicked => {
                    root.popup_toggle();
                }
            }

            WorkspacesWidget {
                horizontal-stretch: 1;
                max-width: parent.width / 3;
                active-workspace: root.active-workspace;
                workspace-occupied: root.workspace-occupied;
            }
            
            HorizontalLayout {
                horizontal-stretch: 1;
                max-width: parent.width / 3;
                spacing: 12px;
                alignment: end;   
                padding-right: 10px;
                
                ScreenshotWidget { }
                ColorizeWidget { }
                
                ClockWidget {
                    time: root.time;
                    date: root.date;
                }
                
                BatteryWidget {
                    percentage: root.battery-percentage;
                    is-charging: root.battery-charging;
                    icon: root.battery-icon;
                }
                
                NetworkWidget {
                    status: root.network-status;
                    connected: root.network-connected;
                    // icon: root.network-icon;
                }
                
                BluetoothWidget {
                    connected: root.bluetooth-connected;
                }

            }
        }
    }
}