import { Theme } from "styles/theme.slint";
import { ClockWidget } from "../app/clock/clock.slint";
import { BatteryWidget } from "../app/battery/battery.slint";
import { NetworkWidget } from "../app/network/network.slint";
import { BluetoothWidget } from "../app/bluetooth/bluetooth.slint";
import { WorkspacesWidget } from "../app/workspaces/workspaces.slint";
import { ScreenshotWidget } from "../app/screenshot/screenshot.slint";
import { ColorizeWidget } from "../app/colorize/colorize.slint";
import { ArticleWidget } from "../app/article/article.slint";
import { MusicIconWidget } from "widgets/music_icon.slint";

export component StatusBarWindow inherits Window {
    title: "Barrita";
    no-frame: true;
    background: transparent;
    always-on-top: true;
    x: 0;
    y: 0;
    width: 1366px;
    height: Theme.bar-height;
    
    in-out property <string> time: "12:00 PM";
    in-out property <string> date: "Mon 04/09";
    
    in-out property <string> battery-percentage: "100%";
    in-out property <int> battery-level: 100;
    in-out property <bool> battery-charging: false;
    in-out property <bool> battery-low: false;
    in-out property <string> battery-icon: "battery_6_bar";
    
    in-out property <string> network-status: "WiFi";
    in-out property <bool> network-connected: true;
    in-out property <string> network-icon: "wifi";
    
    in-out property <bool> bluetooth-connected: false;
    
    in-out property <string> media-status: "stopped";
    in-out property <bool> media-has-player: false;
    in-out property <string> media-title: "Sin música";
    in-out property <string> media-artist: "";
    in-out property <image> media-album-art;
    in-out property <float> media-progress: 0.0;
    in-out property <string> media-progress-time: "0:00";
    in-out property <string> media-total-time: "0:00";
    in-out property <int> media-gif-frame-count: 0;
    in-out property <image> frame_0;
    in-out property <image> frame_1;
    in-out property <int> media-gif-current-frame-index: 0;
    
    in-out property <int> active-workspace: 1;
    in-out property <[bool]> workspace-occupied: [];
    in-out property <int> workspace-total: 8;
    in-out property <[string]> workspace-format: [];
    in-out property <bool> music-popup-visible: false;
    
    callback popup_toggle();
    callback media_play_pause();
    callback media_next();
    callback media_previous();
    callback network_clicked();
    callback colorize_clicked();
    callback screenshot_clicked();
    callback article_clicked();
    callback bluetooth_clicked();
    
    Rectangle {
        min-height: Theme.bar-height;
        // background: Theme.background;
        // opacity: 0.95;
        
        HorizontalLayout {
            spacing: 0px;
            padding-left: 10px;
                               
            MusicIconWidget {
                horizontal-stretch: 1;
                max-width: parent.width / 3;
                status: root.media-status;
                has-player: root.media-has-player;
                title: root.media-title;
                artist: root.media-artist;
                album-art: root.media-album-art;
                frame-count: root.media-gif-frame-count;
                frame-0: root.frame_0;
                frame-1: root.frame_1;
                current-frame-index: root.media-gif-current-frame-index;

                clicked => {
                    root.popup_toggle();
                }
            }

            WorkspacesWidget {
                horizontal-stretch: 1;
                max-width: parent.width / 3;
                active-workspace: root.active-workspace;
                workspace-occupied: root.workspace-occupied;
                total-workspaces: root.workspace-total;
                japanese-numbers: root.workspace-format;
            }
            
            HorizontalLayout {
                horizontal-stretch: 1;
                max-width: parent.width / 3;
                // spacing: 12px;
                alignment: end;
                padding-right: 10px;
                
                ScreenshotWidget {
                    clicked => {
                        root.screenshot_clicked();
                    }
                }
                ColorizeWidget {
                    clicked => {
                        root.colorize_clicked();
                    }
                }
                ArticleWidget {
                    clicked => { root.article_clicked(); }
                }
                
                ClockWidget {
                    time: root.time;
                    date: root.date;
                }
                
                BatteryWidget {
                    percentage: root.battery-percentage;
                    percentage-value: root.battery-level;
                    is-charging: root.battery-charging;
                    is-low: root.battery-low;
                    icon: root.battery-icon;
                }
                
                NetworkWidget {
                    status: root.network-status;
                    connected: root.network-connected;
                    // icon: root.network-icon;
                    clicked => {
                        root.network_clicked();
                    }
                }
                
                BluetoothWidget {
                    connected: root.bluetooth-connected;
                    clicked => {
                        root.bluetooth_clicked();
                    }
                }

            }
        }
    }
}