import { Theme } from "../styles/theme.slint";

export component ScreenshotWidget {
    callback clicked();
    
    Rectangle {
        vertical-stretch: 1;
        
        VerticalLayout {
            alignment: center;
            
            TouchArea {
                clicked => { root.clicked(); }
            }
            
            Text {
                text: "screenshot_region";
                font-family: Theme.icon-font-family;
                font-size: 16px;
                color: Theme.foreground;
            }
        }
    }
}