import { Theme } from "../styles/theme.slint";

export component WorkspacesWidget {
    in-out property <int> active-workspace: 1;
    in-out property <int> total-workspaces: 8;
    
    Rectangle {
        vertical-stretch: 1;
        // background: Theme.background;
        // background: blue;
        border-radius: 12px;
        
        VerticalLayout {
            alignment: center;
            
            HorizontalLayout {
                alignment: center;
                

                Rectangle {
                    background: #00000037;
                    horizontal-stretch: 1;
                    border-radius: 15px;
                    // padding: 5px;

                    HorizontalLayout {
                        alignment: center;
                        spacing: 15px;
                        padding: 2px;
                        
                        
                        for i in root.total-workspaces : Rectangle {
                            width: 22px;
                            height: 22px;
                            border-radius: 15px;
                            background: i == root.active-workspace ? #ebebebe1 : #00000000;

                            Rectangle {
                                width: 5px;
                                height: 5px;
                                border-radius: 4px;
                                background: i == root.active-workspace ? black : Theme.foreground;
                                opacity: i == root.active-workspace ? 1.0 : 1.0;
                            }
                        }
                    }
                }
            }
        }
    }
}