import { Theme } from "../../ui/styles/theme.slint";

export struct PopupMenuItem {
    id: int,
    label: string,
    enabled: bool,
    is-separator: bool,
    is-checked: bool,
}

export global TrayAdapter {
    in-out property <int> item-count;
    in-out property <[image]> item-icons;
    in-out property <[string]> item-tooltips;
    callback item-clicked(int);
    callback right-clicked(int);
    in-out property <[PopupMenuItem]> popup-items:[{ id:1, label:"discord", enabled:false, is-separator:false, is-checked:false }];
    callback menu-item-selected(int);
    callback show-popup;
}

export component TrayWidget inherits Rectangle {
    min-height: 28px;

    Rectangle {
        height: 28px;
        border-radius: 14px;
        background: Theme.surface;

        VerticalLayout {
            alignment: center;
            padding: 3px;

            Rectangle {
                height: 22px;
                border-radius: 11px;
                background: Theme.surface-container-high;
                drop-shadow-color: #00000079;
                drop-shadow-offset-y: 1px;
                drop-shadow-offset-x: 1px;
                drop-shadow-blur: 3px;

                HorizontalLayout {
                    spacing: 8px;
                    alignment: center;
                    padding-left: 10px;
                    padding-right: 10px;

                    for i in TrayAdapter.item-count: Rectangle {
                        visible: i < TrayAdapter.item-icons.length;
                        width: 16px;

                        Image {
                            source: TrayAdapter.item-icons[i];
                            width: 16px;
                            height: 16px;
                            image-fit: contain;
                        }

                        TouchArea {
                            clicked => { TrayAdapter.right-clicked(i); }
                            // clicked => { TrayAdapter.item-clicked(i); }
                            // pointer-event(event) => {
                            //     if (event.kind == PointerEventKind.down && event.button == PointerEventButton.right) {
                            //         TrayAdapter.right-clicked(i);
                            //     }
                            // }
                        }
                    }
                }
            }
        }
    }
}
