import { Theme } from "../../ui/styles/theme.slint";

export global BatteryAdapter {
    in-out property <string> current-percentage: "100%";
    in-out property <int> level: 100;
    in-out property <bool> charging: false;
    in-out property <bool> low: false;
}

export component BatteryWidget {

    VerticalLayout {
        alignment: center;

        Rectangle {
            Rectangle {
                x: 3px;
                y: 8px;
                width: (BatteryAdapter.level * 15px) / 100;
                height: 6px;
                background: BatteryAdapter.low ? #ff4444 : (BatteryAdapter.charging ? #90EE90 : Theme.on-surface);
                clip: true;
            }

            Image {
                source: @image-url("../../assets/icons/battery_android_0.svg");
                width: 26px;
                height: 26px;
                image-fit: contain;
                colorize: Theme.on-surface;
            }
        }
    }

    touch_area := TouchArea {
        // placeholder
    }
}
