import { Theme } from "../../ui/styles/theme.slint";
import { Dashboard } from "dashboard/dashboard.slint";

export component ControlCenter inherits Window {
    no-frame: true;
    width: 800px;
    height: 450px;
    background: transparent;

    touch_area := TouchArea {
        opacity: touch_area.has-hover ? 1.0 : 0.999;

        Rectangle {
            background: transparent;

            HorizontalLayout {
                Rectangle {
                    Path {
                        x: 0;
                        y: 0;
                        width: 15px;
                        height: 15px;
                        fill: Theme.surface-container;

                        MoveTo {
                            x: 0;
                            y: 0;
                        }

                        LineTo {
                            x: 15;
                            y: 0;
                        }

                        LineTo {
                            x: 15;
                            y: 15;
                        }

                        ArcTo {
                            x: 0;
                            y: 0;
                            radius-x: 15;
                            radius-y: 15;
                            large-arc: false;
                            sweep: false;
                        }

                        Close { }
                    }
                }

                Rectangle {
                    background: Theme.surface-container;
                    width: parent.width - 30px;
                    border-bottom-left-radius: 15px;
                    border-bottom-right-radius: 15px;
                    VerticalLayout {
                        Rectangle {
                            height: 30px;
                            background: Theme.surface-container;
                        }

                        Dashboard { }
                    }
                }

                Rectangle {
                    Path {
                        x: 0;
                        y: 0;
                        width: 15px;
                        height: 15px;
                        fill: Theme.surface-container;

                        MoveTo {
                            x: 0;
                            y: 0;
                        }

                        LineTo {
                            x: 15;
                            y: 0;
                        }

                        ArcTo {
                            x: 0;
                            y: 15;
                            radius-x: 15;
                            radius-y: 15;
                            large-arc: false;
                            sweep: false;
                        }

                        Close { }
                    }
                }
            }
        }
    }
}
