import { Theme } from "../../ui/styles/theme.slint";

export global LogoAdapter {
    callback logo-clicked();
}

export component LogoWidget {
    VerticalLayout {
        alignment: center;

        Rectangle {
            width: 28px;
            height: 28px;
            border-radius: 14px;
            border-width: 2px;
            border-color: touch_area.has-hover ? #ffffff42 : transparent;
            background: touch_area.has-hover ? #262722ed : Theme.workspaces_bg_color;

            Image {
                source: @image-url("../../assets/icon.svg");
                width: 16px;
                height: 16px;
            }
        }
    }

    touch_area := TouchArea {
        clicked => {
            LogoAdapter.logo-clicked();
        }
    }
}
