import { Theme } from "../../ui/styles/theme.slint";

export component ScreenshotWidget {
    callback clicked();
    
    Rectangle {
        vertical-stretch: 1;
        
        VerticalLayout {
            alignment: center;
            
            hover_rect := Rectangle {
                height: 30px;
                background: touch_area.has-hover ? #e7e8eb2f : transparent;
                border-width: 1px;
                border-color: touch_area.has-hover ? #ffffff0e : transparent;
                border-radius: 4px;
                
                VerticalLayout {
                    alignment: center;
                    padding-left: 6px;
                    padding-right: 6px;

                    Text {
                        text: "screenshot_region";
                        font-family: Theme.icon-font-family;
                        font-size: 17px;
                        color: Theme.foreground-icon;
                    }
                    
                }
            }
        }
        
        touch_area := TouchArea {
            clicked => { root.clicked(); }
        }
    }
}
