import { Theme } from "../../ui/styles/theme.slint";

export global BluetoothAdapter {
    in-out property <bool> connected: false;
    callback bluetooth-clicked();
}

export component BluetoothWidget {

    VerticalLayout {
        alignment: center;
        padding: -3px;
        Image {
            source: @image-url("../../assets/icons/bluetooth.svg");
            width: 18px;
            height: 18px;
            image-fit: contain;
            colorize: BluetoothAdapter.connected ? Theme.success : Theme.on-surface;
        }
    }
}
