import { Theme } from "../../ui/styles/theme.slint";

export global BluetoothAdapter {
    in-out property <bool> connected: false;
    callback bluetooth-clicked();
}

export component BluetoothWidget {
    Rectangle {
        vertical-stretch: 1;

        touch_area := TouchArea {
            clicked => { BluetoothAdapter.bluetooth-clicked(); }
        }

        VerticalLayout {
            alignment: center;

            hover_rect := Rectangle {
                height: 30px;
                background: touch_area.has-hover ? #e7e8eb2f : transparent;
                border-width: 1px;
                border-color: touch_area.has-hover ? #ffffff0e : transparent;
                border-radius: 4px;

                VerticalLayout {
                    alignment: center;
                    padding-left: 6px;
                    padding-right: 6px;

                    Image {
                        source: @image-url("../../assets/icons/bluetooth.svg");
                        width: 18px;
                        height: 18px;
                        image-fit: contain;
                        colorize: BluetoothAdapter.connected ? Theme.success : Theme.foreground-icon;
                    }
                }
            }
        }
    }
}
