import { Theme } from "../../ui/styles/theme.slint";

export global NetworkAdapter {
    in-out property <string> current-status: "WiFi";
    in-out property <bool> connected: true;
    callback network-clicked();
}

export component NetworkWidget {

    VerticalLayout {
        alignment: center;

        Image {
            source: NetworkAdapter.connected ? @image-url("../../assets/icons/network_wifi.svg") : @image-url("../../assets/icons/globe_2_cancel.svg");
            width: 18px;
            height: 18px;
            image-fit: contain;
            colorize: NetworkAdapter.connected ? Theme.on-surface : Theme.error;
        }
    }

    touch_area := TouchArea {
        clicked => {
            NetworkAdapter.network-clicked();
        }
    }
}
