import { Theme } from "../../ui/styles/theme.slint";

export global NetworkAdapter {
    in-out property <string> current-status: "WiFi";
    in-out property <bool> connected: true;
    callback network-clicked();
}

export component NetworkWidget {
    Rectangle {
        vertical-stretch: 1;

        VerticalLayout {
            alignment: center;

            hover_rect := Rectangle {
                height: 30px;
                background: touch_area.has-hover ? #e7e8eb2f : transparent;
                border-width: 1px;
                border-color: touch_area.has-hover ? #ffffff0e : transparent;
                border-radius: 4px;

                VerticalLayout {
                    alignment: center;
                    padding-left: 6px;
                    padding-right: 6px;

                    Image {
                        source: NetworkAdapter.connected ? @image-url("../../assets/icons/network_wifi.svg") : @image-url("../../assets/icons/globe_2_cancel.svg");
                        width: 18px;
                        height: 18px;
                        image-fit: contain;
                        colorize: NetworkAdapter.connected ? Theme.foreground-icon : Theme.error;
                    }
                }
            }
        }

        touch_area := TouchArea {
            clicked => { NetworkAdapter.network-clicked(); }
        }
    }
}
