import { Theme } from "../styles/theme.slint";

export component BatteryWidget {
    in-out property <string> percentage: "100%";
    in-out property <bool> is-charging: false;
    in-out property <string> icon: "Battery_Android_Frame_Full";
    
    Rectangle {
        vertical-stretch: 1;
        
        VerticalLayout {
            alignment: center;
            
            HorizontalLayout {
                spacing: 4px;
                padding: 0px;
                alignment: center;
                
                Text {
                    text: "Battery_Android_Frame_Full";
                    font-family: Theme.icon-font-family;
                    font-size: 25px;
                    color: Theme.foreground-icon;
                }
                
                // Text {
                //     text: root.percentage;
                //     font-family: Theme.font-family;
                //     font-size: Theme.font-size;
                //     color: root.is-charging ? Theme.warning : Theme.foreground;
                // }
            }
        }
    }
}