import { Theme } from "../styles/theme.slint";

export component BatteryWidget {
    in-out property <string> percentage: "100%";
    in-out property <bool> is-charging: false;
    in-out property <string> icon: "Battery_Android_Frame_Full";
    
    Rectangle {
        vertical-stretch: 1;
        
        VerticalLayout {
            padding-left: 6px;
            padding-right: 6px;
            alignment: center;
            
            HorizontalLayout {
                spacing: 4px;
                padding: 0px;
                alignment: center;
                
                Image {
                    source: @image-url("../../assets/icons/battery_android_frame_full.svg");
                    width: 26px;
                    height: 26px;
                    image-fit: contain;
                    colorize: root.is-charging ? Theme.warning : Theme.foreground-icon;
                }
                
                // Text {
                //     text: root.percentage;
                //     font-family: Theme.font-family;
                //     font-size: Theme.font-size;
                //     color: root.is-charging ? Theme.warning : Theme.foreground;
                // }
            }
        }
    }
}