import { Theme } from "../styles/theme.slint";

export component BluetoothWidget {
    in-out property <bool> connected: false;
    
    Rectangle {
        vertical-stretch: 1;
        
        VerticalLayout {
            padding-left: 6px;
            padding-right: 6px;
            alignment: center;
            
            Image {
                source: @image-url("../../assets/icons/bluetooth.svg");
                width: 18px;
                height: 18px;
                image-fit: contain;
                colorize: root.connected ? Theme.success : Theme.foreground-icon;
            }
        }
    }
}