import { Theme } from "../styles/theme.slint";

export component BluetoothWidget {
    in-out property <bool> connected: false;
    
    Rectangle {
        vertical-stretch: 1;
        
        VerticalLayout {
            alignment: center;
            
            Text {
                text: "bluetooth";
                font-family: Theme.icon-font-family;
                font-size: 18px;
                color: root.connected ? Theme.success : Theme.foreground;
            }
        }
    }
}