import { Theme } from "../styles/theme.slint";

export component ColorizeWidget {
    callback clicked();
    
    Rectangle {
        vertical-stretch: 1;
        
        VerticalLayout {
            alignment: center;
            
            Image {
                source: @image-url("../../assets/icons/colorize.svg");
                width: 16px;
                height: 16px;
                image-fit: contain;
                colorize: Theme.foreground-icon;
            }
        }

        TouchArea {
            clicked => {
                root.clicked();
            }
        }
    }
}