import { Theme } from "../styles/theme.slint";

export component MusicIconWidget {
    in-out property <string> status: "stopped";
    in-out property <bool> has-player: false;
    in-out property <string> title: "Sin música";
    in-out property <string> artist: "";
    in-out property <image> album-art;
    
    callback play-pause();
    callback next();
    callback previous();

    callback clicked;
    
    Rectangle {
        vertical-stretch: 1;

        HorizontalLayout {
            horizontal-stretch: 0;
            alignment: start;
        
            TouchArea {         
                HorizontalLayout {
                    spacing: 4px;

                    // Icono centrado verticalmente
                    VerticalLayout {
                        alignment: center;
                        padding-right: 4px;
                        
                        icon-rect := Rectangle {
                            width: 20px;
                            
                        Image {
                            source: root.has-player ? @image-url("../../assets/icons/motion_play.svg") : @image-url("../../assets/icons/music_off.svg");
                            width: 20px;
                            height: 20px;
                            image-fit: contain;
                            colorize: Theme.foreground-icon;
                        }
                        }
                    }
                    
                    // Album art container
                    VerticalLayout {
                        alignment: center;
                        
                        Rectangle {
                            clip: true;
                            width: 24px;
                            height: 24px;
                            border-radius: Theme.music_album_border_radius * 1px;
                            // background: black;       
                            Image {               
                                source: root.album-art;
                                width: 24px;
                                height: 24px;
                                image-fit: cover;
                            }
                        }
                    }
                    
                    // Artist and Title
                    VerticalLayout {
                        alignment: center;
                        padding-top: 1px;
                        spacing: -2px;
                        
                        Text {
                            font-weight: 600;
                            vertical-alignment: bottom;
                            text: root.artist;
                            font-family: Theme.font-family;
                            font-size: 9.5px;
                            color: Theme.music_artist_color;
                            max-width: 150px;
                            overflow: elide;
                        }
                        
                        Text {
                            font-weight: 600;
                            vertical-alignment: bottom;
                            text: root.title;
                            font-family: Theme.font-family;
                            font-size: 11px;
                            color: Theme.foreground;
                            max-width: 150px;
                            overflow: elide;
                        }
                    }
                }
            
                clicked => {
                    root.clicked();
                }
            }
        }
    }
}