import { Theme } from "../styles/theme.slint";

export component NetworkWidget {
    in-out property <string> status: "WiFi";
    in-out property <bool> connected: true;
    callback clicked();
    
    Rectangle {
        vertical-stretch: 1;
        
        touch_area := TouchArea {
            clicked => { root.clicked(); }
        }
        
        VerticalLayout {
            alignment: center;
            
            hover_rect := Rectangle {
                // width: 30px;
                height: 30px;
                background: touch_area.has-hover ? #e7e8eb2f : transparent;
                border-width: 1px;
                border-color: touch_area.has-hover ? #ffffff0e : transparent;
                border-radius: 4px;
                
                VerticalLayout {
                    alignment: center;
                    padding-left: 6px;
                    padding-right: 6px;
                    
                    Image {
                        source: root.connected ? @image-url("../../assets/icons/network_wifi.svg") : @image-url("../../assets/icons/globe_2_cancel.svg");
                        width: 18px;
                        height: 18px;
                        image-fit: contain;
                        colorize: root.connected ? Theme.foreground-icon : Theme.error;
                    }
                }
            }
        }
    }
}
