import { Theme } from "../styles/theme.slint";

export component NetworkWidget {
    in-out property <string> status: "WiFi";
    in-out property <bool> connected: true;
    callback clicked();
    // in-out property <string> icon: "Network Wifi";
    
    Rectangle {
        vertical-stretch: 1;

        VerticalLayout {
            padding-left: 6px;
            padding-right: 6px;
            alignment: center;
            
            Image {
                source: root.connected ? @image-url("../../assets/icons/network_wifi.svg") : @image-url("../../assets/icons/globe_2_cancel.svg");
                width: 18px;
                height: 18px;
                image-fit: contain;
                colorize: root.connected ? Theme.foreground-icon : Theme.error;
            }
        }
        
        TouchArea {
            clicked => {
                root.clicked();
            }
        }
    }
}