import { Theme } from "../styles/theme.slint";

export component NetworkWidget {
    in-out property <string> status: "WiFi";
    in-out property <bool> connected: true;
    // in-out property <string> icon: "Network Wifi";

    Rectangle {
        vertical-stretch: 1;

        VerticalLayout {
            alignment: center;

            Text {
                text: root.connected ? "Network_Wifi" : "Globe_2_Cancel";
                font-family: Theme.icon-font-family;
                font-size: 16px;
                color: root.connected ? Theme.foreground : Theme.error;
            }
        }
    }
}