import { Theme } from "../styles/theme.slint";

export component ScreenshotWidget {
    callback clicked();
    
    Rectangle {
        vertical-stretch: 1;
        
        VerticalLayout {
            alignment: center;     
            
            // Image {
            //     source: @image-url("../../assets/icons/screenshot_region.svg");
            //     width: 16px;
            //     height: 16px;
            //     image-fit: contain;
            //     colorize: Theme.foreground-icon;
            // }

            Text {
                text: "screenshot_region";
                font-family: Theme.icon-font-family;
                font-size: 17px;
                color: Theme.foreground-icon;
            }
        }

        TouchArea {
            clicked => { root.clicked(); }
        }
    }
}