import { Theme } from "../styles/theme.slint";

export component WorkspacesWidget {
    in-out property <int> active-workspace: 1;
    in-out property <int> total-workspaces: 8;
    in-out property <bool> use-japanese: true;
    in-out property <[string]> japanese-numbers: ["一","二","三","四","五","六","七","八","九","十"];
    in-out property <[bool]> workspace-occupied: [];

    in-out property <color> bg_color: #1e1f1bf6;
    in-out property <color> active_color: #B4CCC1;
    in-out property <color> occupied_bg: #303934;
    in-out property <color> text_active: #303934;
    in-out property <color> text_occupied: #B4C0B9;
    in-out property <color> text_free: #868686;
    in-out property <int> border_radius: 14;

    private property <length> button-size: 22px;
    private property <length> button-spacing: 3px;
    private property <length> margin: 2px;

    Rectangle {
        vertical-stretch: 1;
        
        HorizontalLayout {
            alignment: center;

            VerticalLayout {
                alignment: center;

                Rectangle {
                    background: root.bg_color;
                    border-radius: root.border-radius * 1px;
                    
                    HorizontalLayout {
                        alignment: center;
                        padding: 4px;
                        
                        for i in root.total-workspaces : Rectangle {
                            width: root.button-size;
                            height: root.button-size;

                            private property <bool> occupied:
                                i < root.workspace-occupied.length && root.workspace-occupied[i];

                            private property <bool> isActive:
                                i == root.active-workspace - 1;

                            private property <bool> leftFilled:
                                i > 0 && i - 1 < root.workspace-occupied.length && root.workspace-occupied[i - 1];

                            private property <bool> rightFilled:
                                i + 1 < root.workspace-occupied.length && root.workspace-occupied[i + 1];

                            Rectangle {
                                border-top-left-radius: !leftFilled ? root.button-size/2 : 0px;
                                border-bottom-left-radius: !leftFilled ? root.button-size/2 : 0px;
                                border-top-right-radius: !rightFilled ? root.button-size/2 : 0px;
                                border-bottom-right-radius: !rightFilled ? root.button-size/2 : 0px;
                                background: occupied ? root.occupied_bg : #00000000;
                                opacity: occupied ? 1 : 0.0;
                            }

                            if (isActive) : Rectangle {
                                width: root.button-size * 0.85;
                                height: root.button-size * 0.85;

                                border-radius: self.width / 2;
                                background: root.active_color;

                                x: (root.button-size - self.width) / 2;
                                y: (root.button-size - self.height) / 2;
                            }

                            Text {
                                text: root.use-japanese && i < root.japanese-numbers.length ? root.japanese-numbers[i] : i + 1;
                                font-size: 13px;
                                font-weight: 500;
                                font-family: Theme.font-family;
                                color: isActive ?
                                    root.text_active :
                                    occupied ?
                                        root.text_occupied :
                                        root.text_free;
                                horizontal-alignment: center;
                                vertical-alignment: center;
                            }
                        
                        }
                    }
                }
            }
        }
    }
}